version: '2'
services:
  flaskweb:
    image: flaskstudent:1.0
    container_name: flask_student
    ports:
      - "5000:5000"
    links:
      - mysql
    depends_on:
      - mysql



  mysql:
    image: mysql:5.7
    container_name: flask_mysql
    ports:
      - "13306:3306"
    volumes:
      - /home/flaskmysql/data:/var/lib/mysql
      - /home/flaskmysql/conf/:/etc/mysql/mysql.conf.d/
    environment:
      - MYSQL_ROOT_PASSWORD=123456

 








